# Splash-Text (Hyprland-Logo) über dem Wallpaper deaktivieren
splash = false

# Hintergrundbilder per Block zuweisen (neueres Format)
wallpaper {
    monitor =
    path = /home/emil/Bilder/Wallpaper/wallpap.webp
    fit_mode = cover
}

# Alternativ im klassischen Format (preload + wallpaper):
# preload = /home/benutzer/Bilder/wallpaper.png
# wallpaper = DP-1,/home/benutzer/Bilder/wallpaper.png
